export const data = [
  {
    name: "Stay",
    type: "categorical",
    count: 5000,
    unique_count: 11,
    unique_percent: 0.22,
    missing_count: 0,
    missing_percent: 0.0,
    min_str_length: 4,
    max_str_length: 18,
    avg_str_length: 5.295,
    space_count: 200,
  },
  {
    name: "Price",
    type: "numeric",
    count: 5000,
    unique_count: 500,
    unique_percent: 10,
    missing_count: 20,
    missing_percent: 0.4,
    min_value: 50,
    max_value: 500,
    avg_value: 200,
    space_count: 120,
  },
  {
    name: "Location",
    type: "categorical",
    count: 5000,
    unique_count: 50,
    unique_percent: 1,
    missing_count: 10,
    missing_percent: 0.2,
    min_str_length: 4,
    max_str_length: 18,
    avg_str_length: 5.295,
    space_count: 290,
  },
  {
    name: "Duration",
    type: "numeric",
    count: 5000,
    unique_count: 20,
    unique_percent: 0.4,
    missing_count: 5,
    missing_percent: 0.1,
    min_str_length: 0,
    max_str_length: 20,
    avg_str_length: 5.1,
    space_count: 301,
  },
  {
    name: "Rating",
    type: "numeric",
    count: 5000,
    unique_count: 10,
    unique_percent: 0.2,
    missing_count: 100,
    missing_percent: 2,
    min_str_length: 0,
    max_str_length: 20,
    avg_str_length: 5.1,
    space_count: 341,
  },
  {
    name: "Amenities",
    type: "categorical",
    count: 5000,
    unique_count: 30,
    unique_percent: 0.6,
    missing_count: 50,
    missing_percent: 1,
    min_str_length: 5,
    max_str_length: 25,
    avg_str_length: 8.2,
    space_count: 400,
  },
  {
    name: "Host",
    type: "categorical",
    count: 5000,
    unique_count: 100,
    unique_percent: 2,
    missing_count: 30,
    missing_percent: 0.6,
    min_str_length: 3,
    max_str_length: 20,
    avg_str_length: 6.7,
    space_count: 250,
  },
  {
    name: "Property Type",
    type: "categorical",
    count: 5000,
    unique_count: 20,
    unique_percent: 0.4,
    missing_count: 100,
    missing_percent: 2,
    min_str_length: 5,
    max_str_length: 25,
    avg_str_length: 8.2,
    space_count: 200,
  },
  {
    name: "Reviews",
    type: "numeric",
    count: 5000,
    unique_count: 1000,
    unique_percent: 20,
    missing_count: 50,
    missing_percent: 1,
    min_str_length: 3,
    max_str_length: 25,
    avg_str_length: 2.2,
    space_count: 230,
  },
  {
    name: "Check-in Date",
    type: "date",
    count: 5000,
    unique_count: 500,
    unique_percent: 10,
    missing_count: 0,
    missing_percent: 0,
    min_str_length: 6,
    max_str_length:30,
    avg_str_length: 2.9,
    space_count: 321,
  },
  {
    name: "Check-out Date",
    type: "date",
    count: 5000,
    unique_count: 500,
    unique_percent: 10,
    missing_count: 0,
    missing_percent: 0,
    min_str_length: 8,
    max_str_length: 43,
    avg_str_length: 7.2,
    space_count: 380,
  },
  {
    name: "Guests",
    type: "numeric",
    count: 5000,
    unique_count: 30,
    unique_percent: 0.6,
    missing_count: 10,
    missing_percent: 0.2,
    min_str_length: 3,
    max_str_length: 25,
    avg_str_length: 2.2,
    space_count: 230,
  },
];
